Review site teacher role on professorship update LRN-53 #resolve
FenixEdu/fenixedu-learning pull request #53
Opened 2016-10-31 16:06 UTC by diutsu

2016-11-08 14:13 UTC, Luis-Cruz requested changes

2016-11-08 14:13 UTC, Luis-Cruz commented on src/main/java/org/fenixedu/learning/servlets/FenixEduLearningContextListener.java
> +        Signal.register(ProfessorshipPermissions.PROFESSORSHIP_PERMISSIONS_CHANGED, (DomainObjectEvent<ProfessorshipPermissions> event) ->
This requires an upgrade of the fenixedu-academic module due to changes in the API yet to be released.

2016-11-24 14:58 UTC, Luis-Cruz approved these changes

2016-11-24 19:18 UTC, pedrosan7os approved these changes

2016-11-24 19:18 UTC, merged